# Generated by Django 3.1.7 on 2021-03-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_point', models.CharField(max_length=25)),
                ('start_point', models.CharField(max_length=25)),
                ('sunrise', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
