# Generated by Django 3.1.7 on 2021-03-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20210327_2310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
